serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'chaos_mesh_metrics_1'
        static_configs:
          - targets: 
            - 'chaos-mesh-daemon-metrics-1.local'
            - 'chaos-mesh-dashboards-metrics-1.local'
            - 'chaos-mesh-controller-metrics-1.local'
      - job_name: 'chaos_mesh_metrics_2'
        static_configs:
          - targets: 
            - 'chaos-mesh-daemon-metrics-2.local'
            - 'chaos-mesh-dashboards-metrics-2.local'
            - 'chaos-mesh-controller-metrics-2.local'
      # - job_name: 'chaos_mesh_metrics_I'
      #   static_configs:
      #     - targets: 
      #       - 'chaos-mesh-daemon-metrics-I.local'
      #       - 'chaos-mesh-dashboards-metrics-I.local'
      #       - 'chaos-mesh-controller-metrics-I.local'
