apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
spec:
  remoteCluster: cluster-external
  action: pod-kill
  mode: one
  duration: 30s
  selector:
    namespaces:
      - default
    labelSelectors:
      app: nginx