apiVersion: chaos-mesh.org/v1alpha1
kind: RemoteCluster
metadata:
  name: cluster-external
spec:
  namespace: chaos-mesh
  version: 2.7.0
  kubeConfig:
    secretRef:
      name: chaos-mesh.kubeconfig
      namespace: default
      key: kubeconfig